regedit.exe /s %~dp0/AdvertisingInfo.reg
regedit.exe /s %~dp0/AppHVSI.reg
regedit.exe /s %~dp0/AppModel.reg
regedit.exe /s %~dp0/Audit.reg
regedit.exe /s %~dp0/Camera.reg
regedit.exe /s %~dp0/ccgp.bat
regedit.exe /s %~dp0/Client.reg
regedit.exe /s %~dp0/CloudContent.reg
regedit.exe /s %~dp0/Connect.reg
regedit.exe /s %~dp0/CredentialProvider.reg
regedit.exe /s %~dp0/CredentialsDelegation.reg
regedit.exe /s %~dp0/CredUI.reg
regedit.exe /s %~dp0/DataCollection.reg
regedit.exe /s %~dp0/DeliveryOptimization.reg
regedit.exe /s %~dp0/DeviceGuard.reg
regedit.exe /s %~dp0/DNSClient.reg
regedit.exe /s %~dp0/EarlyLaunch.reg
regedit.exe /s %~dp0/EventLog.reg
regedit.exe /s %~dp0/FacialFeatures.reg
regedit.exe /s %~dp0/Feeds.reg
regedit.exe /s %~dp0/FVE.reg
regedit.exe /s %~dp0/GameDVR.reg
regedit.exe /s %~dp0/GroupPolicy.reg
regedit.exe /s %~dp0/HandwritingErrorReports.reg
regedit.exe /s %~dp0/HardenedPaths.reg
regedit.exe /s %~dp0/HomeGroup.reg
regedit.exe /s %~dp0/Installer.reg
regedit.exe /s %~dp0/International.reg
regedit.exe /s %~dp0/InternetConnectionWizard.reg
regedit.exe /s %~dp0/Kerberos.reg
regedit.exe /s %~dp0/LanmanWorkstation.reg
regedit.exe /s %~dp0/LLTD.reg
regedit.exe /s %~dp0/LocationAndSensors.reg
regedit.exe /s %~dp0/MicrosoftEdge.reg
regedit.exe /s %~dp0/NetworkConnections.reg
regedit.exe /s %~dp0/PassportForWork.reg
regedit.exe /s %~dp0/PCHealth.reg
regedit.exe /s %~dp0/Peernet.reg
regedit.exe /s %~dp0/Personalization.reg
regedit.exe /s %~dp0/PhishingFilter.reg
regedit.exe /s %~dp0/Policies-Explorer.reg
regedit.exe /s %~dp0/Policies-System.reg
regedit.exe /s %~dp0/Power.reg
regedit.exe /s %~dp0/PowerShell.reg
regedit.exe /s %~dp0/PreviewBuilds.reg
regedit.exe /s %~dp0/Printers.reg
regedit.exe /s %~dp0/PushNotifications.reg
regedit.exe /s %~dp0/RegistrationWizardControl.reg
regedit.exe /s %~dp0/Rpc.reg
regedit.exe /s %~dp0/ScriptedDiagnosticsProvider.reg
regedit.exe /s %~dp0/SearchCompanion.reg
regedit.exe /s %~dp0/SettingSync.reg
regedit.exe /s %~dp0/SoftwareProtectionPlatform.reg
regedit.exe /s %~dp0/SoundRecorder.reg
regedit.exe /s %~dp0/Speech.reg
regedit.exe /s %~dp0/SQMClient.reg
regedit.exe /s %~dp0/TabletPC.reg
regedit.exe /s %~dp0/WcmSvc.reg
regedit.exe /s %~dp0/WCN.reg
regedit.exe /s %~dp0/WDI.reg
regedit.exe /s %~dp0/Windows-Explorer.reg
regedit.exe /s %~dp0/Windows-System.reg
regedit.exe /s %~dp0/WindowsDefender.reg
regedit.exe /s %~dp0/WindowsInkWorkspace.reg
regedit.exe /s %~dp0/WindowsMediaPlayer.reg
regedit.exe /s %~dp0/WindowsSearch.reg
regedit.exe /s %~dp0/WindowsStore.reg
regedit.exe /s %~dp0/WindowsUpdate.reg
