regedit.exe /s %~dp0/Assistance.reg
regedit.exe /s %~dp0/Attachments.reg
regedit.exe /s %~dp0/CloudContent.reg
regedit.exe /s %~dp0/ControlPanel.reg
regedit.exe /s %~dp0/CredUI.reg
regedit.exe /s %~dp0/DataCollection.reg
regedit.exe /s %~dp0/EdgeUI.reg
regedit.exe /s %~dp0/Feeds.reg
regedit.exe /s %~dp0/InputPersonalization.reg
regedit.exe /s %~dp0/Installer.reg
regedit.exe /s %~dp0/LocationAndSensors.reg
regedit.exe /s %~dp0/Messenger.reg
regedit.exe /s %~dp0/Network.reg
regedit.exe /s %~dp0/PassportForWork.reg
regedit.exe /s %~dp0/PhishingFilter.reg
regedit.exe /s %~dp0/Policies-Explorer.reg
regedit.exe /s %~dp0/Policies-System.reg
regedit.exe /s %~dp0/Power.reg
regedit.exe /s %~dp0/PowerShell.reg
regedit.exe /s %~dp0/Printers.reg
regedit.exe /s %~dp0/Programs.reg
regedit.exe /s %~dp0/PushNotifications.reg
regedit.exe /s %~dp0/SharedFolders.reg
regedit.exe /s %~dp0/Sidebar.reg
regedit.exe /s %~dp0/SoundRecorder.reg
regedit.exe /s %~dp0/TabletPC.reg
regedit.exe /s %~dp0/Uninstall.reg
regedit.exe /s %~dp0/Windows-Explorer.reg
regedit.exe /s %~dp0/Windows.reg
regedit.exe /s %~dp0/WindowsMediaPlayer.reg
regedit.exe /s %~dp0/WindowsStore.reg
